# Obtain a key here: https://platform.openai.com
openai-key: ""

openai-url: ""

openai-model: "cognitivecomputations/dolphin-2.6-mixtral-8x7b"

# Log conversation messages to server console, useful for catching abuse
log-conversations: true

# Either "system" or "user"; configures the type of message the "preamble"
# will be. "user" is more likely to work with GPT-3.5
preamble-message-type: system
